import Head from "next/head";
import styles from "./Stock.module.css";
import { Heading } from "@chakra-ui/react";
import ItemList from "../ItemList/ItemList";

const Stock = ({categories}) => (
  <main className={styles.container}>
    <Head>
      <title>Pantry - Current Stock</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Heading>Your Pantry</Heading>
    {categories.map( ({id, name, category_items}) => (
      <>
        <Heading as="h2" key={`category-heading-${id}`}>{name}</Heading>
        <ItemList items={category_items} />
      </>
    ))}
  </main>
);

export default Stock;