import Head from "next/head";
import styles from "./Stock.module.css";
import { Heading } from "@chakra-ui/react";
import ItemList from "../ItemList/ItemList";

import dummyData from "../../data/dummyData";

console.log(dummyData.categories);

const Stock = () => (
  <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Heading>Your Pantry</Heading>
    {dummyData.categories.map( ({id, name, items}) => (
      <>
        <Heading as="h2" key={`category-heading-${id}`}>{name}</Heading>
        <ItemList products={items} />
      </>
    ))}
  </div>
)

export default Stock;